name: deploy

on:
  workflow_dispatch: {}
  issues: {}
  issue_comment: {}
  label: {}
  push:
    branches:
      - main

jobs:
  deploy:
    if: false
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: cf
        environment-file: environment.yml
        auto-activate-base: true
        miniforge-version: latest
        miniforge-variant: Mambaforge

    - name: update status page
      shell: bash -l {0}
      run: |
          conda activate cf
          git config --global user.email "pelson.pub+conda-forge@gmail.com"
          git config --global user.name "conda-forge-admin"
          python render_page.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        user_name: conda-forge-admin
        user_email: pelson.pub+conda-forge@gmail.com
